// import { styled } from '@mui/system'
import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import data from '../components/data'
import axios from 'axios'
// import useAxios from 'axios-hooks'
import Link from 'next/link'
import { Container, Grid } from '@mui/material'
import TimeSpace from '../assets/svg/TimeSpaceW.svg'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="main">
        <h1>
          <Image src={TimeSpace} alt="TimeSpace" height={400}></Image>
        </h1>

        <p className="description">
          <code>The space to log and record your competition times</code>
        </p>

        <Grid container spacing={3} className="flex justify-center">
          <Grid item xs={3}>
            <Link href="/records" passHref>
              <div className="card">
                <h2 className="cursor-pointer text-white">View</h2>
              </div>
            </Link>
          </Grid>

          <Grid item xs={3}>
            <Link href="/" passHref>
              <div className="card">
                <h2 className="cursor-pointer text-white">Edit</h2>
              </div>
            </Link>
          </Grid>

          <Grid item xs={3}>
            <Link href="/" passHref>
              <div className="card">
                <h2 className="cursor-pointer text-white">Settings</h2>
              </div>
            </Link>
          </Grid>

          <Grid item xs={3}>
            <Link href="/" passHref>
              <div className="card">
                <h2 className="cursor-pointer text-white">Login</h2>
              </div>
            </Link>
          </Grid>
        </Grid>
      </main>
    </Container>
  )
}

export default Home
