// import { styled } from '@mui/system'
import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'
// import data from '../components/data'
import axios from 'axios'
// import useAxios from 'axios-hooks'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Speedcubing Tracker</a>
        </h1>

        <p className={styles.description}>
          <code>I need a better name for this</code>
        </p>

        <div className={styles.grid}>
          <Link href="/event" passHref>
            <div className={styles.card}>
              <h2>3x3</h2>
            </div>
          </Link>

          <Link href="/records" passHref>
            <div className={styles.card}>
              <h2>Records</h2>
            </div>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home
