// import { styled } from '@mui/system'
import { useState, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'
// import data from '../components/data'
import axios from 'axios'
// import useAxios from 'axios-hooks'
import Link from 'next/link'
import { Container, Grid } from '@mui/material'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Speedcubing Tracker</a>
        </h1>

        <p className={styles.description}>
          <code>I need a better name for this</code>
        </p>

        <Grid container spacing={3} className="flex justify-center">
          {/* <Link href="/event" passHref>
            <div className={styles.card}>
              <h2>3x3</h2>
            </div>
          </Link> */}
          <Grid item xs={3}>
            <Link href="/records" passHref>
              <div className={styles.card}>
                <h2>Records</h2>
              </div>
            </Link>
          </Grid>

          <Grid item xs={3}>
            <Link href="/records" passHref>
              <div className={styles.card}>
                <h2>Records</h2>
              </div>
            </Link>
          </Grid>
        </Grid>
      </main>
    </Container>
  )
}

export default Home
